name: SonarQube Installation Workflow

on:
  push:
    branches:
      - master

jobs:
  install-sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SonarQube
      uses: ./Sonarqube-action  # This assumes your action is in the 'Sonarqube-action' folder

    - name: Start SonarQube Service
      run: |
        sudo systemctl start sonar
        sudo systemctl enable sonar
        sudo systemctl status sonar
