name: SonarQube Installation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install-sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run SonarQube Installation
      uses: ./Sonarqube-action  # Reference the local action

    - name: Verify SonarQube is Running
      run: |
        sudo systemctl status sonar
