name: Test SonarQube Action
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Tester
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run SonarQube Installation
        uses: ./Sonarqube-action  # Reference the local action

      - name: Check SonarQube service status
        run: sudo systemctl status sonar
