# name: SonarQube Installation Workflow

# on:
#   push:
#     branches:
#       - master

# jobs:
#   install-sonarqube:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Install SonarQube
#       uses: ./  # Use the current repository if the action is local

#     - name: Start SonarQube Service
#       run: |
#         sudo systemctl start sonar
#         sudo systemctl enable sonar
#         sudo systemctl status sonar


name: Test SonarQube Action

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SonarQube
        uses: ./sonarqube-action@v1
        with:
          sonarqube_version: '9.9.0.65466'

      - name: Verify SonarQube is running
        run: |
          curl -u admin:admin http://localhost:9000
