# name: SonarQube Installation Workflow

# on:
#   push:
#     branches:
#       - master

# jobs:
#   install-sonarqube:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Install SonarQube
#       uses: ./  # Use the current repository if the action is local

#     - name: Start SonarQube Service
#       run: |
#         sudo systemctl start sonar
#         sudo systemctl enable sonar
#         sudo systemctl status sonar


name: SonarQube Installation

on:
  push:
    branches:
      - master

jobs:
  install-sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SonarQube
      uses: melvinsamuel070/Sonarqube-action@v1  # Replace with the correct username and action name
  # This assumes your action is in the 'Sonarqube-action' folder

    - name: Start SonarQube Service
      run: |
        sudo systemctl start sonar
        sudo systemctl enable sonar
        sudo systemctl status sonar
